language: java
jdk:
- oraclejdk8
install: true

before_install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
- echo $APPLITOOLS_BATCH_ID
- mvn Branches/src/main -B
