language: java
jdk:
- oraclejdk8
before_install:
- export | grep SAUCE_
script: mvn clean test
env:
  global:
  - BUILD_TAG=$TRAVIS_REPO_SLUG+$TRAVIS_BUILD_NUMBER
  - SAUCE_USERNAME=sauce_examples
script:
- export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
- echo $APPLITOOLS_BATCH_ID
