language: java
jdk:
- oraclejdk8
install: true

script:
- mvn install
- export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
- echo $APPLITOOLS_BATCH_ID
- mvn Branches/main -B
