language: java
jdk:
- oraclejdk8

script:
- export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
- echo $APPLITOOLS_BATCH_ID
- cd Branches
- java -version
- mvn exec:java -Dexec.mainClass=src/main -e
