version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
     run:
        command: |
          echo "export APPLITOOLS_BATCH_ID=$CIRCLE_SHA1" >> $BASH_ENV
          cd TestNG
          mvn test