version: 2
jobs:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
     run:
        command: |
          echo "export APPLITOOLS_BATCH_ID=$CIRCLE_SHA1" >> $BASH_ENV
          cd TestNG
          mvn test